spring.application.name=rectrace

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**
spring.servlet.context-path=/rectrace

# Oracle DB Configuration
datasource.url=jdbc:oracle:thin:@sy2i7xwjpd05u21s_high?TNS_ADMIN=/Users/arun/Workspace/Keys/Wallet_SY2I7XWJPD05U21S
datasource.username=ADMIN
datasource.driver-class-name=oracle.jdbc.OracleDriver
datasource.service-name=SY2I7XWJPD05U21S
datasource.db-schema=RECTRACE

# Elasticsearch Configuration
spring.elasticsearch.uris=https://localhost:9200
spring.elasticsearch.username=username
spring.elasticsearch.password=password

# Search Configuration
search-config.location=file:src/main/resources/search-config-v4.json
search-config.location-old=file:src/main/resources/search-config.json

server.port=6088

autosys.db.url=jdbc:oracle:thin:@sy2i7xwjpd05u21s_high?TNS_ADMIN=/Users/arun/Workspace/Keys/Wallet_SY2I7XWJPD05U21S
autosys.db.username=ADMIN
autosys.db.password=Tr9#eLx!Pq72$MvWn8KtZ@CyB
autosys.db.driver-class-name=oracle.jdbc.OracleDriver
autosys.db.schema=AUTOSYS
autosys.db.hikari.minimum-idle=5
autosys.db.hikari.maximum-pool-size=10
autosys.db.hikari.connection-timeout=20000
