spring.application.name=rectrace
# Main Database Configuration
datasource.url=jdbc:oracle:thin:@sy2i7xwjpd05u21s_high?TNS_ADMIN=/Users/arun/Workspace/Keys/Wallet_SY2I7XWJPD05U21S
datasource.username=ADMIN
datasource.password=Tr9#eLx!Pq72$MvWn8KtZ@CyB
datasource.driver-class-name=oracle.jdbc.OracleDriver
datasource.service-name=ADMIN
datasource.db-schema=ADMIN
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# Autosys Database Configuration
autosys.datasource.url=jdbc:oracle:thin:@autosys_db_connection_string?TNS_ADMIN=/path/to/autosys/wallet
autosys.datasource.username=AUTOSYS_USER
autosys.datasource.service-name=AUTOSYS_SERVICE
autosys.datasource.db-schema=AUTOSYS_SCHEMA
autosys.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Elasticsearch Configuration
spring.elasticsearch.uris=https://localhost:9200
spring.elasticsearch.username=username
spring.elasticsearch.password=password

server.port=6088