spring.application.name=autosys-job-explorer
spring.datasource.url=jdbc:oracle:thin:@sy2i7xwjpd05u21s_high?TNS_ADMIN=/Users/arun/Workspace/Keys/Wallet_SY2I7XWJPD05U21S
spring.datasource.username=ADMIN
spring.datasource.password=Tr9#eLx!Pq72$MvWn8KtZ@CyB
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# Elasticsearch Configuration
spring.elasticsearch.uris=https://localhost:9200
spring.elasticsearch.username=username
spring.elasticsearch.password=password

server.port=6088